### ISSUE TITLE
dropdown menu should say current story

### ISSUE THREAD

**Issue by smyerslens** [TheLens/demolitions#50]
I'm somewhat agnostic on this. Beatty says:

when someone chooses a story from the dropdown, the dropdown menu snaps back to "stories." Seems like it should stay on what you chose so you know you're getting what you ask for. 

It would help you remember which one you're on considering the dropdown text is not the same as the headline. Perhaps a checkmark on the one you're on would work.

**Comment by smyerslens** [comment]
Now the dropdown keeps the name of the last story selected when you hit "next." It should clear.

**Comment by ThomasThoren** [comment]
Just pushed a new fix.

Similar to this issue, I'm leaving the dropdown in its default state with "Stories" unless the user selects a story using it. For example, loading the story from a URL or navigating to a story with the previous/next buttons will leave the select menu in its default state instead of updating it. Only direct interaction will change the menu.

**Comment by smyerslens** [comment]
## good

Steve Myers
smyers@thelensnola.org
Special projects editor, The Lens
504-298-9750
@myersnews
