### ISSUE TITLE
Add overall project subhead

### ISSUE THREAD

**Issue by ThomasThoren** [TheLens/demolitions#55]
Not sure which idea ended up being the final choice.

**Comment by smyerslens** [comment]
We didn't settle on one and it could introduce design issues. So let's cancel this.

**Comment by sbeatty** [comment]
No, we need something on first glance that says "demolition" in it. Someone
gets a link to this with someone saying, "Hey look at this!" They really
don't know what they're being served up.

Tom says it shouldn't be a problem to put the subhed above the body copy,
under the "explore new orleans" button. It would be similar to the story
pages.

For that subhed, i'd suggest repeating the title (because the current one
is rather modest and in a corner) and keeping it to one line.

Missing Home: A look at post-Katrina demolitions across city

Steve Beatty
Editor
The Lens
A nonprofit online newsroom for unique coverage of New Orleans
http://TheLensNola.org http://thelensnola.org/
(504) 655-2375

**Comment by smyerslens** [comment]
yeah, a colleague was just reviewing it here and he didn’t know it was about demos.

## I’d cut “across city” — that’s implicit from the button.

Steve Myers
smyers@thelensnola.org
Special projects editor, The Lens
504-298-9750
@myersnews
